// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGaaMHIfmrdNEOvPZ1sazxmfjdbe1hQOY',
    appId: '1:888673883808:android:0224385e75435e5c1bdbc5',
    messagingSenderId: '888673883808',
    projectId: 'fir-31f84',
    databaseURL: 'https://fir-31f84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-31f84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMv7WwBV2ZnwOxDIRQdZO_4nznf7X6sgk',
    appId: '1:888673883808:ios:233143793c29379d1bdbc5',
    messagingSenderId: '888673883808',
    projectId: 'fir-31f84',
    databaseURL: 'https://fir-31f84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-31f84.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
